# Jobs A 2025 Dataset - Cleaning Notebook

## Step 0: Load & Initial Reconnaissance
This notebook handles initial data loading and cleaning decisions.

In [1]:
import pandas as pd
import seaborn as sns
# Load raw dataset (adjust filename if needed)

df = pd.read_csv("../data/raw/dfall_clean.csv", parse_dates = ['created_dt', 'created_date'])

# Quick look
print(df.shape)
print(df.dtypes)
df.head()

(4000, 20)
id                                   int64
title                               object
company_name                        object
category_label                      object
category_tag                        object
country                             object
location_display                    object
location_area                       object
latitude                           float64
longitude                          float64
contract_type                       object
contract_time                       object
salary_min                         float64
salary_max                         float64
salary_mid                         float64
salary_is_predicted                  int64
created_dt             datetime64[ns, UTC]
created_date                datetime64[ns]
redirect_url                        object
adref                               object
dtype: object

,id,title,company_name,category_label,category_tag,country,location_display,location_area,latitude,longitude,contract_type,contract_time,salary_min,salary_max,salary_mid,salary_is_predicted,created_dt,created_date,redirect_url,adref
0,5410474609,Mechanical Pipefitter,Dodd Group,Trade & Construction Jobs,trade-construction-jobs,United Kingdom,"King's Lynn, Norfolk",UK > Eastern England > Norfolk > King's Lynn,52.751999,0.395357,permanent,full_time,40518.74,40518.74,40518.74,1,2025-09-22 09:28:13+00:00,2025-09-22,https://www.adzuna.co.uk/jobs/details/54104746...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTQxMDQ3NDYwOSIsI...
1,5381519011,International Trade Policy Editor [Startup Pol...,Applio Ventures,Graduate Jobs,graduate-jobs,United Kingdom,"London, UK",UK > London,NaN,NaN,permanent,full_time,64000.00,64000.00,64000.00,0,2025-09-03 21:20:59+00:00,2025-09-03,https://www.adzuna.co.uk/jobs/details/53815190...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTM4MTUxOTAxMSIsI...
2,5389371380,Domestic Cleaner,Maid2Clean Suffolk Ltd,Domestic help & Cleaning Jobs,domestic-help-cleaning-jobs,United Kingdom,"Diss, Norfolk",UK > Eastern England > Norfolk > Diss,52.377602,1.106380,permanent,part_time,13.00,13.00,13.00,0,2025-09-08 15:49:25+00:00,2025-09-08,https://www.adzuna.co.uk/jobs/details/53893713...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiRWtwZjc5cWI4QkdZM...
3,5403097985,Early Years BABY Room Leader,Jesters Childcare Essex,Teaching Jobs,teaching-jobs,United Kingdom,UK,UK,NaN,NaN,permanent,full_time,26707.00,29494.00,28100.50,0,2025-09-17 15:00:12+00:00,2025-09-17,https://www.adzuna.co.uk/jobs/details/54030979...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTQwMzA5Nzk4NSIsI...
4,5400306117,Senior Back-End Engineer,Eligible Limited,IT Jobs,it-jobs,United Kingdom,UK,UK,NaN,NaN,permanent,full_time,80000.00,NaN,80000.00,0,2025-09-15 17:51:23+00:00,2025-09-15,https://www.adzuna.co.uk/jobs/details/54003061...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiRWtwZjc5cWI4QkdZM...

## Step 1: Code Assessment
This step reviews entries in the code to highlight suspicious entries

In [2]:
print(f'Number of NaN entries in each column:\n{df.isna().sum()}')

# Review salary columns
df_test_salary = df[(df['salary_min'].isna()==True) & (df['salary_max'].isna()==True) & (df['salary_min'].isna() == True)]
print(f'\nNumber of times that salary min, max, and mid values are all missing: {len(df_test_salary)}')
df_test_salary['salary_is_predicted'].unique()
df_test_predict = df[(df['salary_is_predicted'] == 0)]
df_test_predict

# Check duplicate entries
df_dup_id = df[(df['id'].duplicated() == True)]
print(f'\nNumber of ID entries duplicated: {df['id'].duplicated().sum()}')

Number of NaN entries in each column:
id                        0
title                     0
company_name            214
category_label            0
category_tag              0
country                   0
location_display          0
location_area             0
latitude                743
longitude               743
contract_type          3154
contract_time          3015
salary_min             2456
salary_max             2465
salary_mid             2456
salary_is_predicted       0
created_dt                0
created_date              0
redirect_url              0
adref                     0
dtype: int64

Number of times that salary min, max, and mid values are all missing: 2456

Number of ID entries duplicated: 14

Missing data points found in relevant columns-`salary_min`, `salary_max`, `salary_mid`-as well as in columns describing contract types and locations. Comparing missing entries to the `salary_predicted` columns, it is not dependant on whether the other salary columns are filled or not.

An important note is that the number of `NaN` entries in `salary_min` and `salary_mid` are equal, while `salary_max` has 9 more missing entries. This tells us that `salary_mid` is only reliant on `salary_mid` to calculate a score. We may need to ignore the 9 extra `NaN` entries in `salary_max`

There are 14 `id` entries that are duplicate entries so these must be removed from the dataframe.

In [3]:
missing_salary_mask = df['salary_min'].isna() & df['salary_max'].isna()
check_mask = missing_salary_mask & (df['salary_is_predicted'] == 0)

# Count how many rows meet this condition
count_check = check_mask.sum()
print(f"Number of rows with missing salaries AND salary_is_predicted == 0: {count_check}")
total_missing = missing_salary_mask.sum()
print(f"Total missing salaries: {total_missing}")
print(f"Percentage of missing salaries with salary_is_predicted== 0: {count_check / total_missing:.2%}")

Number of rows with missing salaries AND salary_is_predicted == 0: 2456
Total missing salaries: 2456
Percentage of missing salaries with salary_is_predicted== 0: 100.00%

There is a 100% match on missing salaries where they are not predicted. This means that the missing salary values are as expected and there is no need for correction to these values.

In [4]:
#View the rows where salary_max is missing but salary_min is not missing
df_max_missing = df[df['salary_max'].isna() & df['salary_min'].notna()]
df_max_missing.head()

,id,title,company_name,category_label,category_tag,country,location_display,location_area,latitude,longitude,contract_type,contract_time,salary_min,salary_max,salary_mid,salary_is_predicted,created_dt,created_date,redirect_url,adref
4,5400306117,Senior Back-End Engineer,Eligible Limited,IT Jobs,it-jobs,United Kingdom,UK,UK,NaN,NaN,permanent,full_time,80000.0,NaN,80000.0,0,2025-09-15 17:51:23+00:00,2025-09-15,https://www.adzuna.co.uk/jobs/details/54003061...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiRWtwZjc5cWI4QkdZM...
110,5400486001,Learning and Development (L&D) Partner,Our Future Health,HR & Recruitment Jobs,hr-jobs,United Kingdom,"Bloomsbury, Central London",UK > London > Central London > Bloomsbury,51.518222,-0.123576,contract,full_time,60000.0,NaN,60000.0,0,2025-09-15 20:25:59+00:00,2025-09-15,https://www.adzuna.co.uk/jobs/details/54004860...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTQwMDQ4NjAwMSIsI...
139,5397768976,Well-being Coordinator,St Monica Trust,Social work Jobs,social-work-jobs,United Kingdom,"Westbury Park, Bristol",UK > South West England > Bristol > Westbury Park,51.480458,-2.616741,contract,part_time,26091.0,NaN,26091.0,0,2025-09-13 19:00:49+00:00,2025-09-13,https://www.adzuna.co.uk/jobs/details/53977689...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTM5Nzc2ODk3NiIsI...
210,5392305420,Delivery Driver (Courier),National Network Logistics,Logistics & Warehouse Jobs,logistics-warehouse-jobs,United Kingdom,"Sheffield, South Yorkshire",UK > Yorkshire And The Humber > South Yorkshir...,53.383099,-1.464800,permanent,full_time,200.0,NaN,200.0,0,2025-09-10 12:54:46+00:00,2025-09-10,https://www.adzuna.co.uk/jobs/details/53923054...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTM5MjMwNTQyMCIsI...
411,5392305420,Delivery Driver (Courier),National Network Logistics,Logistics & Warehouse Jobs,logistics-warehouse-jobs,United Kingdom,"Sheffield, South Yorkshire",UK > Yorkshire And The Humber > South Yorkshir...,53.383099,-1.464800,permanent,full_time,200.0,NaN,200.0,0,2025-09-10 12:54:46+00:00,2025-09-10,https://www.adzuna.co.uk/jobs/details/53923054...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTM5MjMwNTQyMCIsI...

In [5]:
#View the rows where salary_min is missing but salary_max is not missing
df_min_missing = df[df['salary_min'].isna() & df['salary_max'].notna()]
df_min_missing.head()

Empty DataFrame
Columns: [id, title, company_name, category_label, category_tag, country, location_display, location_area, latitude, longitude, contract_type, contract_time, salary_min, salary_max, salary_mid, salary_is_predicted, created_dt, created_date, redirect_url, adref]
Index: []

It is clear from this that in cases where only a flat salary is listed instead of a range, the `salary_max` value is not included. Instead of removing these entries, it may be plausible to simply replace these missing values with the listed `salary_min` since it is also the available salary_max. Using the fill method of handling missing values.

In [6]:

# Getting descriptive stats for core features to check for outliers
pd.set_option('display.float_format', '{:,.2f}'.format) #Setting Value display (globally)

print(f"This is the max salary descriptive statistics: {df['salary_max'].describe()}")

This is the max salary descriptive statistics: count       1,535.00
mean       56,278.04
std       222,339.02
min             1.00
25%        25,438.00
50%        40,000.00
75%        61,561.34
max     5,000,000.00
Name: salary_max, dtype: float64

In [7]:
 print(f"This is the minimum salary descriptive statistics: {df['salary_min'].describe()}")

This is the minimum salary descriptive statistics: count       1,544.00
mean       45,494.48
std        93,658.83
min             0.00
25%        22,000.00
50%        34,616.17
75%        55,306.24
max     2,000,000.00
Name: salary_min, dtype: float64

In [8]:
 print(f"This is the mid salary descriptive statistics: {df['salary_mid'].describe()}")

This is the mid salary descriptive statistics: count       1,544.00
mean       50,802.85
std       156,765.57
min             1.00
25%        24,050.00
50%        37,500.00
75%        57,500.00
max     3,500,000.00
Name: salary_mid, dtype: float64

Some jobs with very high minimum and maximum salaries may need to be analyzed seperatly from the main population of salaries. These jobs may skew the analysis to much and will be reviewed in cleaning decsions.

In [9]:
# Outliers for salary_min
Q1_min = df['salary_min'].quantile(0.25)
Q3_min = df['salary_min'].quantile(0.75)
IQR_min = Q3_min - Q1_min
print("\nOutliers for salary_min:")
df[(df['salary_min'] < (Q1_min - 1.5 * IQR_min)) | (df['salary_min'] > (Q3_min + 1.5 * IQR_min))]

Outliers for salary_min:

,id,title,company_name,category_label,category_tag,country,location_display,location_area,latitude,longitude,contract_type,contract_time,salary_min,salary_max,salary_mid,salary_is_predicted,created_dt,created_date,redirect_url,adref
259,5389284985,Sr. Solutions Engineer New Logos - LONDON - UN...,Park Lane Recruitment,IT Jobs,it-jobs,United Kingdom,UK,UK,NaN,NaN,permanent,full_time,"160,000.00","160,000.00","160,000.00",0,2025-09-08 13:19:55+00:00,2025-09-08,https://www.adzuna.co.uk/jobs/details/53892849...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoib3VZNjl0cWI4QkdZM...
430,5383002843,General Practitioner Job,Merco Medical Staffing Limited,Healthcare & Nursing Jobs,healthcare-nursing-jobs,United Kingdom,"Wilmington, Dartford",UK > South East England > Kent > Dartford > Wi...,51.44,0.21,NaN,NaN,"174,720.00","174,720.00","174,720.00",0,2025-09-04 14:30:00+00:00,2025-09-04,https://www.adzuna.co.uk/jobs/details/53830028...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTM4MzAwMjg0MyIsI...
504,5382475352,Sales Executive,The N2 Company,Sales Jobs,sales-jobs,USA,"Scranton, Lackawanna County",US > Pennsylvania > Lackawanna County > Scranton,41.41,-75.67,NaN,NaN,"106,746.46","106,746.46","106,746.46",1,2025-09-03 23:57:35+00:00,2025-09-03,https://www.adzuna.com/details/5382475352?utm_...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTM4MjQ3NTM1MiIsI...
516,5269749716,Rad Tech - Cardiac CATH Lab,Sanford Health,Healthcare & Nursing Jobs,healthcare-nursing-jobs,USA,"Stanton, Mercer County",US > North Dakota > Mercer County > Stanton,47.31,-101.39,NaN,full_time,"244,472.34","244,472.34","244,472.34",1,2025-06-26 12:32:07+00:00,2025-06-26,https://www.adzuna.com/details/5269749716?utm_...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoielA5Ml90cWI4Qkdad...
517,5350649148,Unit Manager RN Registered Nurse,Complete Care at Silver Lake LLC,Healthcare & Nursing Jobs,healthcare-nursing-jobs,USA,"Wyoming, Kent County",US > Delaware > Kent County > Wyoming,39.17,-75.57,NaN,NaN,"128,153.30","128,153.30","128,153.30",1,2025-08-13 12:13:58+00:00,2025-08-13,https://www.adzuna.com/details/5350649148?utm_...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTM1MDY0OTE0OCIsI...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1266,5348364073,Oberarzt Anästhesiologie & Intensivmedizin (m/...,NeoStaff Consulting - Personalberatung im Gesu...,Stellen aus Gesundheitswesen & Pflege,healthcare-nursing-jobs,Germany,"Bielefeld, Nordrhein-Westfalen",Deutschland > Nordrhein-Westfalen > Bielefeld,52.02,8.54,permanent,full_time,"160,000.00","160,000.00","160,000.00",0,2025-08-11 23:37:47+00:00,2025-08-11,https://www.adzuna.de/details/5348364073?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiRkxhckc5dWI4QkdZM...
1761,5232758209,Sevran – Devenez Agent Immobilier chez Vendez...,Blockos,Emplois Immobilier,property-jobs,France,"Sevran, Le Raincy",France > Ile-de-France > Seine-Saint-Denis > L...,48.94,2.53,permanent,full_time,"2,000,000.00","5,000,000.00","3,500,000.00",0,2025-06-04 15:10:52+00:00,2025-06-04,https://www.adzuna.fr/details/5232758209?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiWGh6SExOdWI4QkdMW...
1786,5391006929,Comptable Généraliste Junior (H/F) à Quimperlé...,FAB Group,Emplois Comptabilité et Finance,accounting-finance-jobs,France,"Quimperlé, Quimper",France > Bretagne > Finistère > Quimper > Quim...,47.90,-3.53,permanent,full_time,"384,000.00","504,000.00","444,000.00",0,2025-09-09 21:40:10+00:00,2025-09-09,https://www.adzuna.fr/details/5391006929?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTM5MTAwNjkyOSIsI...
1893,5232758200,Fontenay-sous-Bois – Devenez Agent Immobilier...,Blockos,Emplois Immobilier,property-jobs,France,"Fontenay-sous-Bois, Nogent-sur-Marne",France > Ile-de-France > Val-de-Marne > Nogent...,48.85,2.47,permanent,full_time,"2,000,000.00","5,000,000.00","3,500,000.00",0,2025-06-04 15:10:52+00:00,2025-06-04,https://www.adzuna.fr/details/5232758200?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoic2xkbU1OdWI4QkdMW...
1913,5234604807,Athis-Mons – Devenez Agent Immobilier chez Ve...,Blockos,Emplois Immobilier,property-jobs,France,"Athis-Mons, Palaiseau",France > Ile-de-France > Essonne > Palaiseau >...,48.71,2.38,permanent,full_time,"2,000,000.00","5,000,000.00","3,500,000.00",0,2025-06-05 15:15:15+00:00,2025-06-05,https://www.adzuna.fr/details/5234604807?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTIzNDYwNDgwNyIsI...

In [10]:

# Outliers for salary_max
Q1_max = df['salary_max'].quantile(0.25)
Q3_max = df['salary_max'].quantile(0.75)
IQR_max = Q3_max - Q1_max
print("\nOutliers for salary_max:")
df[(df['salary_max'] < (Q1_max - 1.5 * IQR_max)) | (df['salary_max'] > (Q3_max + 1.5 * IQR_max))]

Outliers for salary_max:

,id,title,company_name,category_label,category_tag,country,location_display,location_area,latitude,longitude,contract_type,contract_time,salary_min,salary_max,salary_mid,salary_is_predicted,created_dt,created_date,redirect_url,adref
27,5414133640,(URGENT) Overseas Associate Dentist or Associa...,Woole & Scarra,Healthcare & Nursing Jobs,healthcare-nursing-jobs,United Kingdom,"Llanidloes, Powys",UK > Wales > Powys > Llanidloes,52.45,-3.54,permanent,full_time,"100,000.00","300,000.00","200,000.00",0,2025-09-25 04:20:08+00:00,2025-09-25,https://www.adzuna.co.uk/jobs/details/54141336...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTQxNDEzMzY0MCIsI...
156,5403358918,SEN Teaching Assistant,Vision for Education,Teaching Jobs,teaching-jobs,United Kingdom,"Bebside, Blyth",UK > North East England > Northumberland > Bly...,55.14,-1.56,permanent,NaN,"104,000.00","130,000.00","117,000.00",0,2025-09-17 19:40:14+00:00,2025-09-17,https://www.adzuna.co.uk/jobs/details/54033589...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTQwMzM1ODkxOCIsI...
245,5417092340,(URGENT) Overseas Associate Dentist (Kilmarnock),Woole & Scarra,Healthcare & Nursing Jobs,healthcare-nursing-jobs,United Kingdom,"Kilmarnock, East Ayrshire",UK > Scotland > East Ayrshire > Kilmarnock,55.61,-4.50,permanent,full_time,"100,000.00","300,000.00","200,000.00",0,2025-09-27 08:33:24+00:00,2025-09-27,https://www.adzuna.co.uk/jobs/details/54170923...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiR0xpazlOcWI4QkdZM...
259,5389284985,Sr. Solutions Engineer New Logos - LONDON - UN...,Park Lane Recruitment,IT Jobs,it-jobs,United Kingdom,UK,UK,NaN,NaN,permanent,full_time,"160,000.00","160,000.00","160,000.00",0,2025-09-08 13:19:55+00:00,2025-09-08,https://www.adzuna.co.uk/jobs/details/53892849...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoib3VZNjl0cWI4QkdZM...
283,5404722281,IT Manager （Casino， Mandarin or Cantonese spea...,AP Advisory,Hospitality & Catering Jobs,hospitality-catering-jobs,United Kingdom,"London, UK",UK > London,51.50,-0.14,permanent,full_time,"100,000.00","120,000.00","110,000.00",0,2025-09-18 11:06:08+00:00,2025-09-18,https://www.adzuna.co.uk/jobs/details/54047222...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoib3VZNjl0cWI4QkdZM...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1761,5232758209,Sevran – Devenez Agent Immobilier chez Vendez...,Blockos,Emplois Immobilier,property-jobs,France,"Sevran, Le Raincy",France > Ile-de-France > Seine-Saint-Denis > L...,48.94,2.53,permanent,full_time,"2,000,000.00","5,000,000.00","3,500,000.00",0,2025-06-04 15:10:52+00:00,2025-06-04,https://www.adzuna.fr/details/5232758209?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiWGh6SExOdWI4QkdMW...
1786,5391006929,Comptable Généraliste Junior (H/F) à Quimperlé...,FAB Group,Emplois Comptabilité et Finance,accounting-finance-jobs,France,"Quimperlé, Quimper",France > Bretagne > Finistère > Quimper > Quim...,47.90,-3.53,permanent,full_time,"384,000.00","504,000.00","444,000.00",0,2025-09-09 21:40:10+00:00,2025-09-09,https://www.adzuna.fr/details/5391006929?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTM5MTAwNjkyOSIsI...
1870,5416639347,Médecin du travail ou médecin généraliste — H/F,Pierre Tona Consulting,Emplois Soins de santé et infirmiers,healthcare-nursing-jobs,France,"Compiègne-Nord, Compiègne",France > Hauts-De-France > Oise > Compiègne > ...,49.42,2.82,permanent,full_time,"85,000.00","125,000.00","105,000.00",0,2025-09-27 01:36:53+00:00,2025-09-27,https://www.adzuna.fr/details/5416639347?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoic2xkbU1OdWI4QkdMW...
1893,5232758200,Fontenay-sous-Bois – Devenez Agent Immobilier...,Blockos,Emplois Immobilier,property-jobs,France,"Fontenay-sous-Bois, Nogent-sur-Marne",France > Ile-de-France > Val-de-Marne > Nogent...,48.85,2.47,permanent,full_time,"2,000,000.00","5,000,000.00","3,500,000.00",0,2025-06-04 15:10:52+00:00,2025-06-04,https://www.adzuna.fr/details/5232758200?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoic2xkbU1OdWI4QkdMW...
1913,5234604807,Athis-Mons – Devenez Agent Immobilier chez Ve...,Blockos,Emplois Immobilier,property-jobs,France,"Athis-Mons, Palaiseau",France > Ile-de-France > Essonne > Palaiseau >...,48.71,2.38,permanent,full_time,"2,000,000.00","5,000,000.00","3,500,000.00",0,2025-06-05 15:15:15+00:00,2025-06-05,https://www.adzuna.fr/details/5234604807?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTIzNDYwNDgwNyIsI...

In [11]:

# Outliers for salary_mid
Q1_mid = df['salary_mid'].quantile(0.25)
Q3_mid = df['salary_mid'].quantile(0.75)
IQR_mid = Q3_mid - Q1_mid
print("\nOutliers for salary_mid:")
df[(df['salary_mid'] < (Q1_mid - 1.5 * IQR_mid)) | (df['salary_mid'] > (Q3_mid + 1.5 * IQR_mid))]

Outliers for salary_mid:

,id,title,company_name,category_label,category_tag,country,location_display,location_area,latitude,longitude,contract_type,contract_time,salary_min,salary_max,salary_mid,salary_is_predicted,created_dt,created_date,redirect_url,adref
27,5414133640,(URGENT) Overseas Associate Dentist or Associa...,Woole & Scarra,Healthcare & Nursing Jobs,healthcare-nursing-jobs,United Kingdom,"Llanidloes, Powys",UK > Wales > Powys > Llanidloes,52.45,-3.54,permanent,full_time,"100,000.00","300,000.00","200,000.00",0,2025-09-25 04:20:08+00:00,2025-09-25,https://www.adzuna.co.uk/jobs/details/54141336...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTQxNDEzMzY0MCIsI...
156,5403358918,SEN Teaching Assistant,Vision for Education,Teaching Jobs,teaching-jobs,United Kingdom,"Bebside, Blyth",UK > North East England > Northumberland > Bly...,55.14,-1.56,permanent,NaN,"104,000.00","130,000.00","117,000.00",0,2025-09-17 19:40:14+00:00,2025-09-17,https://www.adzuna.co.uk/jobs/details/54033589...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTQwMzM1ODkxOCIsI...
245,5417092340,(URGENT) Overseas Associate Dentist (Kilmarnock),Woole & Scarra,Healthcare & Nursing Jobs,healthcare-nursing-jobs,United Kingdom,"Kilmarnock, East Ayrshire",UK > Scotland > East Ayrshire > Kilmarnock,55.61,-4.50,permanent,full_time,"100,000.00","300,000.00","200,000.00",0,2025-09-27 08:33:24+00:00,2025-09-27,https://www.adzuna.co.uk/jobs/details/54170923...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiR0xpazlOcWI4QkdZM...
259,5389284985,Sr. Solutions Engineer New Logos - LONDON - UN...,Park Lane Recruitment,IT Jobs,it-jobs,United Kingdom,UK,UK,NaN,NaN,permanent,full_time,"160,000.00","160,000.00","160,000.00",0,2025-09-08 13:19:55+00:00,2025-09-08,https://www.adzuna.co.uk/jobs/details/53892849...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoib3VZNjl0cWI4QkdZM...
283,5404722281,IT Manager （Casino， Mandarin or Cantonese spea...,AP Advisory,Hospitality & Catering Jobs,hospitality-catering-jobs,United Kingdom,"London, UK",UK > London,51.50,-0.14,permanent,full_time,"100,000.00","120,000.00","110,000.00",0,2025-09-18 11:06:08+00:00,2025-09-18,https://www.adzuna.co.uk/jobs/details/54047222...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoib3VZNjl0cWI4QkdZM...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1266,5348364073,Oberarzt Anästhesiologie & Intensivmedizin (m/...,NeoStaff Consulting - Personalberatung im Gesu...,Stellen aus Gesundheitswesen & Pflege,healthcare-nursing-jobs,Germany,"Bielefeld, Nordrhein-Westfalen",Deutschland > Nordrhein-Westfalen > Bielefeld,52.02,8.54,permanent,full_time,"160,000.00","160,000.00","160,000.00",0,2025-08-11 23:37:47+00:00,2025-08-11,https://www.adzuna.de/details/5348364073?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiRkxhckc5dWI4QkdZM...
1761,5232758209,Sevran – Devenez Agent Immobilier chez Vendez...,Blockos,Emplois Immobilier,property-jobs,France,"Sevran, Le Raincy",France > Ile-de-France > Seine-Saint-Denis > L...,48.94,2.53,permanent,full_time,"2,000,000.00","5,000,000.00","3,500,000.00",0,2025-06-04 15:10:52+00:00,2025-06-04,https://www.adzuna.fr/details/5232758209?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiWGh6SExOdWI4QkdMW...
1786,5391006929,Comptable Généraliste Junior (H/F) à Quimperlé...,FAB Group,Emplois Comptabilité et Finance,accounting-finance-jobs,France,"Quimperlé, Quimper",France > Bretagne > Finistère > Quimper > Quim...,47.90,-3.53,permanent,full_time,"384,000.00","504,000.00","444,000.00",0,2025-09-09 21:40:10+00:00,2025-09-09,https://www.adzuna.fr/details/5391006929?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTM5MTAwNjkyOSIsI...
1893,5232758200,Fontenay-sous-Bois – Devenez Agent Immobilier...,Blockos,Emplois Immobilier,property-jobs,France,"Fontenay-sous-Bois, Nogent-sur-Marne",France > Ile-de-France > Val-de-Marne > Nogent...,48.85,2.47,permanent,full_time,"2,000,000.00","5,000,000.00","3,500,000.00",0,2025-06-04 15:10:52+00:00,2025-06-04,https://www.adzuna.fr/details/5232758200?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoic2xkbU1OdWI4QkdMW...
1913,5234604807,Athis-Mons – Devenez Agent Immobilier chez Ve...,Blockos,Emplois Immobilier,property-jobs,France,"Athis-Mons, Palaiseau",France > Ile-de-France > Essonne > Palaiseau >...,48.71,2.38,permanent,full_time,"2,000,000.00","5,000,000.00","3,500,000.00",0,2025-06-05 15:15:15+00:00,2025-06-05,https://www.adzuna.fr/details/5234604807?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTIzNDYwNDgwNyIsI...

There are a total of 12 rows qualifying as outliers for the data. All of which currently skew the data upward. Specifically, the 3 rows for the `company_name`: Blockos appear worth isolating from the rest of the data.

In [12]:
#Show rows with missing company
df[df['company_name'].isna()]

,id,title,company_name,category_label,category_tag,country,location_display,location_area,latitude,longitude,contract_type,contract_time,salary_min,salary_max,salary_mid,salary_is_predicted,created_dt,created_date,redirect_url,adref
1768,5327710716,"29/07/2025 - Ingénieur(e) Systèmes, Réseaux et...",NaN,Unknown,unknown,France,France,France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2025-07-30 01:20:06+00:00,2025-07-30,https://www.adzuna.fr/details/5327710716?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiWGh6SExOdWI4QkdMW...
1769,5403418186,Aide-soignant / Aide-soignante en EHPAD nuit H/F,NaN,Unknown,unknown,France,"Toulouse 15e Canton, Toulouse",France > Occitanie > Haute-Garonne > Toulouse ...,43.75,1.49,NaN,NaN,NaN,NaN,NaN,0,2025-09-17 21:31:06+00:00,2025-09-17,https://www.adzuna.fr/details/5403418186?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiWGh6SExOdWI4QkdMW...
1770,5361394799,20/08/2025 - PREPARATEUR/TRICE EN PHARMACIE HO...,NaN,Unknown,unknown,France,"Valréas, Avignon",France > Provence-Alpes-Côte d'Azur > Vaucluse...,44.32,4.95,NaN,NaN,NaN,NaN,NaN,0,2025-08-21 01:29:52+00:00,2025-08-21,https://www.adzuna.fr/details/5361394799?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiWGh6SExOdWI4QkdMW...
1781,5403417185,Finisseur / Finisseuse de l'industrie du béton,NaN,Unknown,unknown,France,"Deauville, Calvados",France > Normandie > Calvados > Deauville,49.34,0.12,NaN,NaN,NaN,NaN,NaN,0,2025-09-17 21:30:55+00:00,2025-09-17,https://www.adzuna.fr/details/5403417185?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiWGh6SExOdWI4QkdMW...
1785,5412447510,Cariste Magasinier H/F,NaN,Unknown,unknown,France,"Epernay 2e Canton, Epernay",France > Grand-Est > Marne > Epernay > Epernay...,49.03,3.96,NaN,NaN,NaN,NaN,NaN,0,2025-09-23 21:25:29+00:00,2025-09-23,https://www.adzuna.fr/details/5412447510?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiWGh6SExOdWI4QkdMW...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3488,5406684830,Pintor,NaN,Unknown,unknown,Spain,España,España,NaN,NaN,NaN,NaN,"6,000.00","7,200.00","6,600.00",0,2025-09-19 11:16:13+00:00,2025-09-19,https://www.adzuna.es/details/5406684830?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTQwNjY4NDgzMCIsI...
3493,5295840160,No se encuentra una traducción directa en el d...,NaN,Unknown,unknown,Spain,España,España,NaN,NaN,NaN,NaN,216.00,216.00,216.00,0,2025-07-10 15:31:27+00:00,2025-07-10,https://www.adzuna.es/details/5295840160?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTI5NTg0MDE2MCIsI...
3494,5295839841,Colocador de azulejos,NaN,Unknown,unknown,Spain,España,España,NaN,NaN,NaN,NaN,"31,200.00","31,200.00","31,200.00",0,2025-07-10 15:31:25+00:00,2025-07-10,https://www.adzuna.es/details/5295839841?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiWFBYUVpOdWI4Qkdad...
3496,5392358204,Mecánico industrial,NaN,Unknown,unknown,Spain,España,España,NaN,NaN,NaN,NaN,"28,800.00","28,800.00","28,800.00",0,2025-09-10 15:14:48+00:00,2025-09-10,https://www.adzuna.es/details/5392358204?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiWFBYUVpOdWI4Qkdad...
3497,5295840219,Tapicero,NaN,Unknown,unknown,Spain,España,España,NaN,NaN,NaN,NaN,"6,000.00","6,600.00","6,300.00",0,2025-07-10 15:31:27+00:00,2025-07-10,https://www.adzuna.es/details/5295840219?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTI5NTg0MDIxOSIsI...

In [13]:
#Show rows where id matches another row id
df[df['id'].duplicated(keep=False)]

,id,title,company_name,category_label,category_tag,country,location_display,location_area,latitude,longitude,contract_type,contract_time,salary_min,salary_max,salary_mid,salary_is_predicted,created_dt,created_date,redirect_url,adref
210,5392305420,Delivery Driver (Courier),National Network Logistics,Logistics & Warehouse Jobs,logistics-warehouse-jobs,United Kingdom,"Sheffield, South Yorkshire",UK > Yorkshire And The Humber > South Yorkshir...,53.38,-1.46,permanent,full_time,200.00,NaN,200.00,0,2025-09-10 12:54:46+00:00,2025-09-10,https://www.adzuna.co.uk/jobs/details/53923054...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTM5MjMwNTQyMCIsI...
411,5392305420,Delivery Driver (Courier),National Network Logistics,Logistics & Warehouse Jobs,logistics-warehouse-jobs,United Kingdom,"Sheffield, South Yorkshire",UK > Yorkshire And The Humber > South Yorkshir...,53.38,-1.46,permanent,full_time,200.00,NaN,200.00,0,2025-09-10 12:54:46+00:00,2025-09-10,https://www.adzuna.co.uk/jobs/details/53923054...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTM5MjMwNTQyMCIsI...
1509,5332303911,CONSEILLER PATRIMONIAL (MIA) (H/F),Capfinances,Emplois Autres/Général,other-general-jobs,France,"Coulonges-sur-l'Autize, Niort",France > Nouvelle-Aquitaine > Deux-Sèvres > Ni...,46.37,-0.60,contract,NaN,NaN,NaN,NaN,0,2025-08-01 19:17:20+00:00,2025-08-01,https://www.adzuna.fr/details/5332303911?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTMzMjMwMzkxMSIsI...
1530,5392524422,Apprenti(e) Carrossier / peintre H/F (Basé à C...,Renault,Emplois Autres/Général,other-general-jobs,France,"Seine-et-Marne, Ile-de-France",France > Ile-de-France > Seine-et-Marne,48.67,2.84,contract,NaN,NaN,NaN,NaN,0,2025-09-10 18:24:47+00:00,2025-09-10,https://www.adzuna.fr/details/5392524422?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTM5MjUyNDQyMiIsI...
1538,5396952296,INFIRMIER ANESTHÉSISTE DE (F/H),Agence Appel médical Bloc PACA,Emplois Soins de santé et infirmiers,healthcare-nursing-jobs,France,"Contes, Nice",France > Provence-Alpes-Côte d'Azur > Alpes-Ma...,43.76,7.32,contract,NaN,NaN,NaN,NaN,0,2025-09-13 02:03:47+00:00,2025-09-13,https://www.adzuna.fr/details/5396952296?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiZ0F6ckk5dWI4QkdZM...
1541,5379966210,INFIRMIER ANESTHÉSISTE DE (F/H),Ag Glisy Bloc Nord Normandie,Emplois Soins de santé et infirmiers,healthcare-nursing-jobs,France,"Darnétal, Rouen",France > Normandie > Seine-Maritime > Rouen > ...,49.43,1.26,contract,NaN,NaN,NaN,NaN,0,2025-09-02 21:56:29+00:00,2025-09-02,https://www.adzuna.fr/details/5379966210?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTM3OTk2NjIxMCIsI...
1545,5377597266,AUXILIAIRE DE PUÉRICULTURE (F/H),Agence Appel Médical Petite Enfance PACA,Emplois Soins de santé et infirmiers,healthcare-nursing-jobs,France,"Le Cannet, Grasse",France > Provence-Alpes-Côte d'Azur > Alpes-Ma...,43.55,7.01,permanent,NaN,NaN,NaN,NaN,0,2025-09-01 13:57:50+00:00,2025-09-01,https://www.adzuna.fr/details/5377597266?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiZ0F6ckk5dWI4QkdZM...
1588,5396952296,INFIRMIER ANESTHÉSISTE DE (F/H),Agence Appel médical Bloc PACA,Emplois Soins de santé et infirmiers,healthcare-nursing-jobs,France,"Contes, Nice",France > Provence-Alpes-Côte d'Azur > Alpes-Ma...,43.76,7.32,contract,NaN,NaN,NaN,NaN,0,2025-09-13 02:03:47+00:00,2025-09-13,https://www.adzuna.fr/details/5396952296?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiSWlTUEpkdWI4QkdMW...
1608,5332303911,CONSEILLER PATRIMONIAL (MIA) (H/F),Capfinances,Emplois Autres/Général,other-general-jobs,France,"Coulonges-sur-l'Autize, Niort",France > Nouvelle-Aquitaine > Deux-Sèvres > Ni...,46.37,-0.60,contract,NaN,NaN,NaN,NaN,0,2025-08-01 19:17:20+00:00,2025-08-01,https://www.adzuna.fr/details/5332303911?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTMzMjMwMzkxMSIsI...
1621,5379966210,INFIRMIER ANESTHÉSISTE DE (F/H),Ag Glisy Bloc Nord Normandie,Emplois Soins de santé et infirmiers,healthcare-nursing-jobs,France,"Darnétal, Rouen",France > Normandie > Seine-Maritime > Rouen > ...,49.43,1.26,contract,NaN,NaN,NaN,NaN,0,2025-09-02 21:56:29+00:00,2025-09-02,https://www.adzuna.fr/details/5379966210?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiYW9VLUo5dWI4QkdZM...
1692,5392524422,Apprenti(e) Carrossier / peintre H/F (Basé à C...,Renault,Emplois Autres/Général,other-general-jobs,France,"Seine-et-Marne, Ile-de-France",France > Ile-de-France > Seine-et-Marne,48.67,2.84,contract,NaN,NaN,NaN,NaN,0,2025-09-10 18:24:47+00:00,2025-09-10,https://www.adzuna.fr/details/5392524422?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTM5MjUyNDQyMiIsI...
1750,5377597266,AUXILIAIRE DE PUÉRICULTURE (F/H),Agence Appel Médical Petite Enfance PACA,Emplois Soins de santé et infirmiers,healthcare-nursing-jobs,France,"Le Cannet, Grasse",France > Provence-Alpes-Côte d'Azur > Alpes-Ma...,43.55,7.01,permanent,NaN,NaN,NaN,NaN,0,2025-09-01 13:57:50+00:00,2025-09-01,https://www.adzuna.fr/details/5377597266?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiWGh6SExOdWI4QkdMW...
3019,5295840928,Drukarz (Alemania),NaN,Unknown,unknown,Spain,España,España,NaN,NaN,NaN,NaN,"33,600.00","33,600.00","33,600.00",0,2025-07-10 15:31:31+00:00,2025-07-10,https://www.adzuna.es/details/5295840928?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiWkJxM1Z0dWI4QkdZM...
3022,5393884424,Senior Android Engineer - Quick Commerce,Delivery Hero,Otros trabajos,other-general-jobs,Spain,Barcelona,España > Cataluña > Barcelona > Barcelona,41.38,2.17,NaN,NaN,NaN,NaN,NaN,0,2025-09-11 10:44:08+00:00,2025-09-11,https://www.adzuna.es/details/5393884424?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTM5Mzg4NDQyNCIsI...
3027,5377839132,Digital Customer Success Manager (D-CSM) - Cro...,SAP,Unknown,unknown,Spain,Barcelona,España > Cataluña > Barcelona > Barcelona,41.38,2.17,NaN,NaN,NaN,NaN,NaN,0,2025-09-01 17:33:06+00:00,2025-09-01,https://www.adzuna.es/details/5377839132?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiWkJxM1Z0dWI4QkdZM...
3035,5415710477,Business Development Manager,Aerones,Trabajos en ventas,sales-jobs,Spain,España,España,NaN,NaN,NaN,NaN,70.00,125.00,97.50,0,2025-09-26 16:43:40+00:00,2025-09-26,https://www.adzuna.es/details/5415710477?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTQxNTcxMDQ3NyIsI...
3040,5291766837,Web Designer,Jobgether,Trabajos en diseño y artes gráficas,creative-design-jobs,Spain,España,España,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2025-07-08 15:32:39+00:00,2025-07-08,https://www.adzuna.es/details/5291766837?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTI5MTc2NjgzNyIsI...
3043,5379347673,Technical Support Engineer (Product),Nexthink,Trabajos en informática,it-jobs,Spain,Madrid,España > Comunidad de Madrid > Madrid > Madrid,40.43,-3.72,NaN,NaN,NaN,NaN,NaN,0,2025-09-02 10:21:22+00:00,2025-09-02,https://www.adzuna.es/details/5379347673?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTM3OTM0NzY3MyIsI...
3047,5391918840,Técnico/a Comercial y desarrollo de productos,SGS,Trabajos en consultoría,consultancy-jobs,Spain,Cáceres,España > Extremadura > Cáceres > Cáceres,39.47,-6.37,NaN,NaN,NaN,NaN,NaN,0,2025-09-10 04:40:50+00:00,2025-09-10,https://www.adzuna.es/details/5391918840?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiWkJxM1Z0dWI4QkdZM...
3063,5393884424,Senior Android Engineer - Quick Commerce,Delivery Hero,Otros trabajos,other-general-jobs,Spain,Barcelona,España > Cataluña > Barcelona > Barcelona,41.38,2.17,NaN,NaN,NaN,NaN,NaN,0,2025-09-11 10:44:08+00:00,2025-09-11,https://www.adzuna.es/details/5393884424?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiY2psV1dOdWI4QkdMW...
3195,5390805540,Vendedor/a - Ibiza - (30 horas),Rituals,Trabajos en ventas,sales-jobs,Spain,"Ibiza, Islas Baleares",España > Islas Baleares > Islas Baleares > Ibiza,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2025-09-09 16:39:20+00:00,2025-09-09,https://www.adzuna.es/details/5390805540?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiaUxCMVc5dWI4Qkdad...
3237,5391918840,Técnico/a Comercial y desarrollo de productos,SGS,Trabajos en consultoría,consultancy-jobs,Spain,Cáceres,España > Extremadura > Cáceres > Cáceres,39.47,-6.37,NaN,NaN,NaN,NaN,NaN,0,2025-09-10 04:40:50+00:00,2025-09-10,https://www.adzuna.es/details/5391918840?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoicmdBU1hkdWI4QkdZM...
3286,5295840928,Drukarz (Alemania),NaN,Unknown,unknown,Spain,España,España,NaN,NaN,NaN,NaN,"33,600.00","33,600.00","33,600.00",0,2025-07-10 15:31:31+00:00,2025-07-10,https://www.adzuna.es/details/5295840928?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTI5NTg0MDkyOCIsI...
3287,5291766837,Web Designer,Jobgether,Trabajos en diseño y artes gráficas,creative-design-jobs,Spain,España,España,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2025-07-08 15:32:39+00:00,2025-07-08,https://www.adzuna.es/details/5291766837?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiVXNPelh0dWI4QkdMW...
3313,5415710477,Business Development Manager,Aerones,Trabajos en ventas,sales-jobs,Spain,España,España,NaN,NaN,NaN,NaN,70.00,125.00,97.50,0,2025-09-26 16:43:40+00:00,2025-09-26,https://www.adzuna.es/details/5415710477?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTQxNTcxMDQ3NyIsI...
3338,5390805540,Vendedor/a - Ibiza - (30 horas),Rituals,Trabajos en ventas,sales-jobs,Spain,"Ibiza, Islas Baleares",España > Islas Baleares > Islas Baleares > Ibiza,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2025-09-09 16:39:20+00:00,2025-09-09,https://www.adzuna.es/details/5390805540?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiZkhJOVlOdWI4QkdMW...
3396,5379347673,Technical Support Engineer (Product),Nexthink,Trabajos en informática,it-jobs,Spain,Madrid,España > Comunidad de Madrid > Madrid > Madrid,40.43,-3.72,NaN,NaN,NaN,NaN,NaN,0,2025-09-02 10:21:22+00:00,2025-09-02,https://www.adzuna.es/details/5379347673?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTM3OTM0NzY3MyIsI...
3403,5377839132,Digital Customer Success Manager (D-CSM) - Cro...,SAP,Unknown,unknown,Spain,Barcelona,España > Cataluña > Barcelona > Barcelona,41.38,2.17,NaN,NaN,NaN,NaN,NaN,0,2025-09-01 17:33:06+00:00,2025-09-01,https://www.adzuna.es/details/5377839132?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTM3NzgzOTEzMiIsI...

In [14]:
# Show jobs with salary_min under 1000
df[df['salary_min'] < 1000]

,id,title,company_name,category_label,category_tag,country,location_display,location_area,latitude,longitude,contract_type,contract_time,salary_min,salary_max,salary_mid,salary_is_predicted,created_dt,created_date,redirect_url,adref
2,5389371380,Domestic Cleaner,Maid2Clean Suffolk Ltd,Domestic help & Cleaning Jobs,domestic-help-cleaning-jobs,United Kingdom,"Diss, Norfolk",UK > Eastern England > Norfolk > Diss,52.38,1.11,permanent,part_time,13.00,13.00,13.00,0,2025-09-08 15:49:25+00:00,2025-09-08,https://www.adzuna.co.uk/jobs/details/53893713...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiRWtwZjc5cWI4QkdZM...
6,5404864465,Full Stack Software Engineer,Marshall Wolfe Ltd,IT Jobs,it-jobs,United Kingdom,UK,UK,NaN,NaN,permanent,full_time,0.00,"60,000.00","30,000.00",0,2025-09-18 14:32:46+00:00,2025-09-18,https://www.adzuna.co.uk/jobs/details/54048644...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTQwNDg2NDQ2NSIsI...
9,5404874544,Assembly Line Operative – Full Time,Euro Communications Distribution Limited,Logistics & Warehouse Jobs,logistics-warehouse-jobs,United Kingdom,"Wolverhampton, West Midlands",UK > West Midlands > Wolverhampton,52.59,-2.13,permanent,full_time,7.00,12.00,9.50,0,2025-09-18 14:51:06+00:00,2025-09-18,https://www.adzuna.co.uk/jobs/details/54048745...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTQwNDg3NDU0NCIsI...
12,5384670531,Care Assistant - Social Care,Home Instead Chelmsford,Healthcare & Nursing Jobs,healthcare-nursing-jobs,United Kingdom,"Hatfield Peverel, Chelmsford",UK > Eastern England > Essex > Chelmsford > Ha...,51.78,0.59,permanent,part_time,13.00,13.00,13.00,0,2025-09-05 11:21:59+00:00,2025-09-05,https://www.adzuna.co.uk/jobs/details/53846705...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiRWtwZjc5cWI4QkdZM...
15,5392245855,Credit Review,Global Corporate Investment Bank,Accounting & Finance Jobs,accounting-finance-jobs,United Kingdom,"London, UK",UK > London,51.50,-0.14,permanent,full_time,0.00,"100,000.00","50,000.00",0,2025-09-10 11:31:44+00:00,2025-09-10,https://www.adzuna.co.uk/jobs/details/53922458...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiRWtwZjc5cWI4QkdZM...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3580,5415370326,Italian Customer Service Agent in Greece - Ful...,Patrique Mercier Recruitment JP,Kundendienststellen,customer-services-jobs,Switzerland,Schweiz,Schweiz,NaN,NaN,NaN,full_time,16.00,20.00,18.00,0,2025-09-26 15:24:32+00:00,2025-09-26,https://www.adzuna.ch/details/5415370326?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTQxNTM3MDMyNiIsI...
3788,5415370488,German Speaking Customer Service for High-End ...,Patrique Mercier Recruitment JP,Kundendienststellen,customer-services-jobs,Switzerland,Schweiz,Schweiz,NaN,NaN,NaN,full_time,20.00,23.00,21.50,0,2025-09-26 15:24:33+00:00,2025-09-26,https://www.adzuna.ch/details/5415370488?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiU2xDWGJ0dWI4QkdMW...
3819,5415370406,French Speaking Customer Service Representativ...,Patrique Mercier Recruitment JP,Kundendienststellen,customer-services-jobs,Switzerland,Schweiz,Schweiz,NaN,NaN,NaN,full_time,16.00,20.00,18.00,0,2025-09-26 15:24:32+00:00,2025-09-26,https://www.adzuna.ch/details/5415370406?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTQxNTM3MDQwNiIsI...
3989,5415370607,Italian Speaking Jobs in Greece - Paid Relocat...,Patrique Mercier Recruitment JP,Kundendienststellen,customer-services-jobs,Switzerland,Schweiz,Schweiz,NaN,NaN,NaN,full_time,16.00,20.00,18.00,0,2025-09-26 15:24:34+00:00,2025-09-26,https://www.adzuna.ch/details/5415370607?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTQxNTM3MDYwNyIsI...
3996,5415370352,German Speaking Support for Social Media - Ins...,Patrique Mercier Recruitment JP,Sonstige/Allgemeine Stellen,other-general-jobs,Switzerland,Schweiz,Schweiz,NaN,NaN,NaN,full_time,20.00,23.00,21.50,0,2025-09-26 15:24:32+00:00,2025-09-26,https://www.adzuna.ch/details/5415370352?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiNkxnSGRkdWI4Qkdad...

## Step 2: Cleaning Decisions
This step resolves problems discovered in Step 1

Right now I think we should remove any duplicated rows, isolate the rows where there are significant outliers but not all. Just the few in the millions as they are too big to ignore. I feel the others could be relevant data points and interesting to see.

In [15]:
# Remove Duplicates for further analysis and create a copy of the df
df_no_duplicates = df[~df['id'].duplicated(keep=False)].copy()

The first step in cleaning the data was to remove the duplicated rows. From inspecting the time stamps of these duplicates it was decided that they were simply misclicks or errors by the internet scrapper used to compile a large chunk of this dataset.

In [16]:
# Build the mask 
mask = df_no_duplicates['salary_max'].isna() & df_no_duplicates['salary_min'].notna()

# Fillmax salaries with min
df_no_duplicates.loc[mask, 'salary_max'] = df_no_duplicates.loc[mask, 'salary_min']

There were several rows where the `salary_max` was missing but not the `salary_min`. Since in these cases they should be treated as the same value we elected to use the fill method to fill in these missing max salary values.

In [17]:
# Keep only rows where salary_max is between 1000 and 1,000,000
df_filtered = df[(df['salary_max'] >= 1000) & (df['salary_max'] <= 1_000_000)]
df_filtered

,id,title,company_name,category_label,category_tag,country,location_display,location_area,latitude,longitude,contract_type,contract_time,salary_min,salary_max,salary_mid,salary_is_predicted,created_dt,created_date,redirect_url,adref
0,5410474609,Mechanical Pipefitter,Dodd Group,Trade & Construction Jobs,trade-construction-jobs,United Kingdom,"King's Lynn, Norfolk",UK > Eastern England > Norfolk > King's Lynn,52.75,0.40,permanent,full_time,"40,518.74","40,518.74","40,518.74",1,2025-09-22 09:28:13+00:00,2025-09-22,https://www.adzuna.co.uk/jobs/details/54104746...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTQxMDQ3NDYwOSIsI...
1,5381519011,International Trade Policy Editor [Startup Pol...,Applio Ventures,Graduate Jobs,graduate-jobs,United Kingdom,"London, UK",UK > London,NaN,NaN,permanent,full_time,"64,000.00","64,000.00","64,000.00",0,2025-09-03 21:20:59+00:00,2025-09-03,https://www.adzuna.co.uk/jobs/details/53815190...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTM4MTUxOTAxMSIsI...
3,5403097985,Early Years BABY Room Leader,Jesters Childcare Essex,Teaching Jobs,teaching-jobs,United Kingdom,UK,UK,NaN,NaN,permanent,full_time,"26,707.00","29,494.00","28,100.50",0,2025-09-17 15:00:12+00:00,2025-09-17,https://www.adzuna.co.uk/jobs/details/54030979...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTQwMzA5Nzk4NSIsI...
5,5404665589,Computer Systems Validation specialist,North Star Consulting UK,Scientific & QA Jobs,scientific-qa-jobs,United Kingdom,"Newcastle Upon Tyne, Tyne & Wear",UK > North East England > Tyne & Wear > Newcas...,NaN,NaN,permanent,full_time,"65,000.00","65,000.00","65,000.00",0,2025-09-18 10:29:32+00:00,2025-09-18,https://www.adzuna.co.uk/jobs/details/54046655...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiRWtwZjc5cWI4QkdZM...
6,5404864465,Full Stack Software Engineer,Marshall Wolfe Ltd,IT Jobs,it-jobs,United Kingdom,UK,UK,NaN,NaN,permanent,full_time,0.00,"60,000.00","30,000.00",0,2025-09-18 14:32:46+00:00,2025-09-18,https://www.adzuna.co.uk/jobs/details/54048644...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTQwNDg2NDQ2NSIsI...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3778,5410584501,Web3 Institutional Business Development (commi...,prePO,"Stellen aus PR, Werbung & Marketing",pr-advertising-marketing-jobs,Switzerland,Zug,Schweiz > Kanton Zug > Zug > Zug,47.17,8.52,NaN,part_time,"1,000.00","1,000.00","1,000.00",0,2025-09-22 14:50:50+00:00,2025-09-22,https://www.adzuna.ch/details/5410584501?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTQxMDU4NDUwMSIsI...
3856,5167245269,Zimmermann,fledro Personal Consulting AG,Stellen aus Handel & Bau,trade-construction-jobs,Switzerland,"Basel, Basel-Stadt",Schweiz > Kanton Basel-Stadt > Basel-Stadt > B...,47.56,7.59,NaN,NaN,"66,000.00","78,000.00","72,000.00",0,2025-04-28 21:19:59+00:00,2025-04-28,https://www.adzuna.ch/details/5167245269?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoia0Z2amNkdWI4QkdZM...
3952,5341000428,FaGe oder ein/e Dipl. Pflegefachfrau / Fachman...,fledro Personal Consulting AG,Stellen aus Gesundheitswesen & Pflege,healthcare-nursing-jobs,Switzerland,"Basel, Basel-Stadt",Schweiz > Kanton Basel-Stadt > Basel-Stadt > B...,47.56,7.59,NaN,NaN,"66,000.00","78,000.00","72,000.00",0,2025-08-07 01:20:24+00:00,2025-08-07,https://www.adzuna.ch/details/5341000428?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTM0MTAwMDQyOCIsI...
3960,5404287831,Kundenmaler 100%,fledro Personal Consulting AG,Stellen aus Handel & Bau,trade-construction-jobs,Switzerland,"Basel, Basel-Stadt",Schweiz > Kanton Basel-Stadt > Basel-Stadt > B...,47.56,7.59,NaN,NaN,"66,000.00","78,000.00","72,000.00",0,2025-09-18 02:52:24+00:00,2025-09-18,https://www.adzuna.ch/details/5404287831?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiNkxnSGRkdWI4Qkdad...
3963,5416683229,CATRAMISTA / IMPERMEABILIZZATORE,Orienta SA,Stellen aus Handel & Bau,trade-construction-jobs,Switzerland,"Mendrisio, Kanton Tessin",Schweiz > Kanton Tessin > Mendrisio,45.87,8.99,NaN,NaN,"42,000.00","54,000.00","48,000.00",0,2025-09-27 02:27:15+00:00,2025-09-27,https://www.adzuna.ch/details/5416683229?utm_m...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiNkxnSGRkdWI4Qkdad...

Due to the large effect they have on the dataset, we decided to remove salaries that were over 1 million dollars in compensation. It was also decided to remove salary information under $1,000 as these were most likely hourly pay rates that were detected by the sweeper.

In [18]:
df_filtered.to_pickle("../data/cleaned_data.pkl")